import { Prisma } from "@prisma/client";

/**
 * Represents an item in the shopping cart.
 * Each item contains information about the product, quantity, and price.
 *
 * @typedef {Object} CartItem
 * @property {number} productId - The unique identifier of the product.
 * @property {string} productName - The name of the product.
 * @property {number} quantity - The quantity of the product ordered.
 * @property {number} price - The price of a single product.
 */
export type CartItem = {
  productId: number;
  productName: string;
  quantity: number;
  price: number;
};

/**
 * Prisma type for creating a new order in the database.
 * This type is automatically generated by Prisma and used in the OrderService.
 *
 * @typedef {Prisma.OrderCreateInput} OrderCreateInput
 * @see https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#create
 */
export type OrderCreateInput = Prisma.OrderCreateInput;

/**
 * Prisma type for updating an existing order in the database.
 * This type is automatically generated by Prisma and used in the OrderService.
 *
 * @typedef {Prisma.OrderUpdateInput} OrderUpdateInput
 * @see https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#update
 */
export type OrderUpdateInput = Prisma.OrderUpdateInput;
