version: "3.9"

services:
  nestjs:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4001:4000"
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - mongodb

  nextjs:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env.docker
    depends_on:
      - nestjs

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
