version: "3.9"

services:
  nestjs:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb

  nextjs:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - nestjs

  postgres:
    image: postgres
    ports:
      - "5434:5433"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_NAME}
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
