version: "3.9"

services:
  nestjs:
    image: "${DB_NAME}-nestjs"
    ports:
      - "4000:4000"
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - mongodb

  nextjs:
    image: "${DB_NAME}-nextjs"
    ports:
      - "3000:3000"
    depends_on:
      - nestjs

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MONGO_INITDB_DATABASE: "${DB_NAME}"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
