version: "3.9"

services:
  nestjs:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - .env
    depends_on:
      - postgres

  nextjs:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - nestjs

  postgres:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
